"""A rescued sample must be visible in the consensus record.

Two harness rescue paths exist and both change the reasoning effort of the sample they rescue:

  * `stub_rejected` - the terminal turn was a tool-call envelope rather than a report (GEV s1,
    2026-09-20: 1,861 chars of `<tool_call>` accepted as the deliverable 29 minutes in). The
    harness then forces a memorandum turn at `think: "low"` with `num_predict` 32768.
  * `forced_report` - a turn generated by the forced-report path, which fires when both tool
    budgets are exhausted or the budget gate trips.

`chat_with_tools` returns both in `meta`, and `stub_rejected` is persisted to the sample's own
`_research_snapshot.json`. But `consensus_valuation` copied only four keys out of `meta`
(`done_reason`, `generated_tokens`, `eval_rate`, `eval_duration_s`), so neither ever reached
`runs[]` or `consensus.json`. A band could therefore mix a sample written at reduced reasoning
effort with normal siblings and no consumer could tell - a false-confidence defect in the
verdict that the audit system is supposed to be able to read.

This is an ANNOTATION. It must not move direction or size.
"""
import pytest

import depth_pipeline as dp
from tools.audit_202608.consensus_valuation import rescue_status


@pytest.fixture(autouse=True)
def _no_prior(monkeypatch):
    """Keep these tests hermetic - Task 1's detector reads the real ledger otherwise."""
    monkeypatch.setattr(dp, "_prior_verdict", lambda t, l: None)


# ---- rescue_status: meta -> flags, no Ollama needed ------------------------------------

def test_stub_rejected_is_read_from_meta():
    assert rescue_status({"stub_rejected": True})["stub_rejected"] is True
    assert rescue_status({"stub_rejected": False})["stub_rejected"] is False


def test_forced_report_is_read_from_any_turn():
    meta = {"turns": [{"turn": 1}, {"turn": 2, "forced_report": True}, {"turn": 3}]}
    assert rescue_status(meta)["forced_report"] is True


def test_forced_report_is_false_when_no_turn_was_forced():
    meta = {"turns": [{"turn": 1}, {"turn": 2, "budget_exhausted": True}]}
    assert rescue_status(meta)["forced_report"] is False


def test_absent_and_empty_meta_are_both_clear():
    # Asserts the individual MARKERS, not exact-dict equality: an exact-dict assertion on a
    # returned contract breaks the moment a marker is added, which is exactly what happened when
    # `budget_exhausted` was added. The intent is "nothing is reported as rescued".
    for meta in (None, {}):
        st = rescue_status(meta)
        assert st["stub_rejected"] is False
        assert st["forced_report"] is False
        assert st["budget_exhausted"] is False


def test_turns_being_absent_none_or_malformed_does_not_raise():
    # The snapshot on disk predates `turns` entirely, so absence is the NORMAL case.
    for meta in ({"turns": None}, {"turns": []}, {"turns": [None, "x", 7]}):
        st = rescue_status(meta)
        assert st["stub_rejected"] is False
        assert st["forced_report"] is False
        assert st["budget_exhausted"] is False


# ---- band_verdict: the flag ------------------------------------------------------------

def _doc(runs, price=100.0, iv=100.0):
    return {
        "ticker": "RESCUE", "price": price, "samples_run": len(runs), "converged": True,
        "spread_pct": 2.0, "median_iv": iv, "early_stop": len(runs) == 2,
        "runs": runs, "scorecard": {"base_iv": iv},
    }


def _run(n, iv=100.0, **kw):
    r = {"sample": n, "iv": iv, "plausible": True, "truncated": False}
    r.update(kw)
    return r


def test_a_rescued_used_sample_raises_the_flag():
    v = dp.band_verdict(_doc([_run(1, stub_rejected=True), _run(2)]))
    assert "LOW_EFFORT_RESCUE" in v["flags"]
    assert "rescue" in (v.get("reason") or "").lower() or "reduced" in (v.get("reason") or "").lower()


def test_a_forced_report_raises_the_flag():
    v = dp.band_verdict(_doc([_run(1, forced_report=True), _run(2)]))
    assert "LOW_EFFORT_RESCUE" in v["flags"]


def test_a_clean_set_is_silent():
    v = dp.band_verdict(_doc([_run(1, stub_rejected=False, forced_report=False), _run(2)]))
    assert "LOW_EFFORT_RESCUE" not in (v.get("flags") or [])


def test_a_rescued_sample_that_was_NOT_used_does_not_raise_the_flag():
    # An implausible or truncated sample does not reach the band, so its rescue status is
    # irrelevant to the published number.
    v = dp.band_verdict(_doc([_run(1, stub_rejected=True, plausible=False), _run(2)]))
    assert "LOW_EFFORT_RESCUE" not in (v.get("flags") or [])


def test_legacy_runs_without_the_keys_do_not_raise():
    # Every consensus.json written before this change lacks both keys.
    v = dp.band_verdict(_doc([_run(1), _run(2)]))
    assert "LOW_EFFORT_RESCUE" not in (v.get("flags") or [])


def test_the_flag_does_not_move_direction_or_size(monkeypatch):
    clean = dp.band_verdict(_doc([_run(1), _run(2)]))
    rescued = dp.band_verdict(_doc([_run(1, stub_rejected=True), _run(2)]))
    assert rescued["direction"] == clean["direction"]
    assert rescued["size_hint"] == clean["size_hint"]
    assert rescued["kelly_fraction_pct"] == clean["kelly_fraction_pct"]


# ---- the SECOND forced path: budgets exhausted (review I1) ------------------------------
# `analyst_tools.py` tags two different rescued turns:
#   :452 `forced_report: True`     - the stub-rejection retry, `think: "low"`, num_predict 32768
#   :513 `budget_exhausted: True`  - both tool budgets reached, forced at the SAME `think`
# Only the first was ever read, so a budget-exhausted sample published as if it had concluded
# naturally. They are NOT the same condition: only `forced_report` lowers the reasoning effort,
# so lumping the budget path into `LOW_EFFORT_RESCUE` would make that flag's name false. It gets
# its own flag instead, and the docstring that claimed `forced_report` covered the budget path
# was corrected.

def test_budget_exhausted_is_read_from_any_turn():
    meta = {"turns": [{"turn": 1}, {"turn": 2, "budget_exhausted": True}, {"turn": 3}]}
    assert rescue_status(meta)["budget_exhausted"] is True


def test_budget_exhausted_is_false_when_no_turn_exhausted_its_budget():
    meta = {"turns": [{"turn": 1}, {"turn": 2, "forced_report": True}]}
    assert rescue_status(meta)["budget_exhausted"] is False


def test_the_two_forced_paths_do_not_imply_each_other():
    only_stub_retry = rescue_status({"turns": [{"forced_report": True}]})
    assert only_stub_retry["forced_report"] is True
    assert only_stub_retry["budget_exhausted"] is False
    only_budget = rescue_status({"turns": [{"budget_exhausted": True}]})
    assert only_budget["forced_report"] is False
    assert only_budget["budget_exhausted"] is True


def test_budget_exhausted_is_clear_on_absent_and_malformed_meta():
    for meta in (None, {}, {"turns": None}, {"turns": []}, {"turns": [None, "x", 7]}):
        assert rescue_status(meta)["budget_exhausted"] is False


def test_a_budget_exhausted_used_sample_raises_its_own_flag():
    v = dp.band_verdict(_doc([_run(1, budget_exhausted=True), _run(2)]))
    assert "FORCED_REPORT" in v["flags"]
    assert "budget" in (v.get("reason") or "").lower()


def test_a_budget_exhausted_sample_does_not_claim_low_effort():
    """The distinction, pinned: budgets exhausted is not reduced reasoning effort."""
    v = dp.band_verdict(_doc([_run(1, budget_exhausted=True), _run(2)]))
    assert "LOW_EFFORT_RESCUE" not in (v.get("flags") or [])


def test_a_budget_exhausted_sample_that_was_NOT_used_does_not_raise():
    v = dp.band_verdict(_doc([_run(1, budget_exhausted=True, plausible=False), _run(2)]))
    assert "FORCED_REPORT" not in (v.get("flags") or [])


def test_legacy_runs_without_budget_exhausted_do_not_raise():
    v = dp.band_verdict(_doc([_run(1), _run(2)]))
    assert "FORCED_REPORT" not in (v.get("flags") or [])


def test_the_forced_report_flag_does_not_move_direction_or_size():
    clean = dp.band_verdict(_doc([_run(1), _run(2)]))
    forced = dp.band_verdict(_doc([_run(1, budget_exhausted=True), _run(2)]))
    assert forced["direction"] == clean["direction"]
    assert forced["size_hint"] == clean["size_hint"]
    assert forced["kelly_fraction_pct"] == clean["kelly_fraction_pct"]
